version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app:latest
    container_name: app
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - web

  db:
    image: "postgres:latest"
    container_name: db
    ports:
      - 5434:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_CLIENT_DB},${POSTGRES_SUBSCRIPTION_DB}
    volumes:
      - ./docker-postgresql-multiple-databases.sh:/docker-entrypoint-initdb.d/docker-postgresql-multiple-databases.sh
      - pg-data:/var/lib/postgresql/test/data
    networks:
      - web

networks:
  web:

volumes:
  pg-data: